# Generated by Django 3.2.12 on 2022-04-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0005_alter_loggedinuser_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loggedinuser',
            options={'default_permissions': (('view', 'delete'),)},
        ),
    ]
